[build]
  cmd = "echo 'build.cmd' ; go build -o ~/step-task cmd/app/main.go"
  exclude_dir = ["tmp", "vendor"]
  exclude_regex = ["_test.go", "*.md"]
  full_bin = "echo 'build.full_bin' ; ~/step-task"
  include_ext = ["go", "toml", "yml", "env"]
  include_file = ["Makefile"]
  post_cmd = ["echo 'build.post_cmd'", "make app_main_test"]
  pre_cmd = [
    "reset",
    "echo 'build.pre_cmd'",
    "gofmt -w -s .",
    "goimports -w .",
    "go mod tidy",
  ]
