root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = ""
  cmd = "echo 'build.cmd'"
  delay = 1000
  exclude_dir = [
    "assets",
    "testdata",
    "tmp",
    "vendor",
    "db"
  ]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = true
  follow_symlink = true
  full_bin = "echo 'build.full_bin' ; go run cmd/app/main.go"
  include_dir = []
  include_ext = [
    "go",
    "html",
    "tmpl",
    "toml",
    "tpl",
    "yml",
  ]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = [
    "make app_main_test"
  ]
  pre_cmd = [
    "reset",
    "gofmt -w -s .",
    "goimports -w .",
    "go mod tidy",
  ]
  rerun = false
  rerun_delay = 500
  send_interrupt = true
  stop_on_error = true

[color]
  app = "red"
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = true
  keep_scroll = true
